test_contact.py::ContactTest::test_contact_page
--------------------------------------------------------------------
Last Page: https://practice.automationbro.com/contact/
  Browser: chrome (102.0.5005.115)
   Driver: chromedriver (102.0.5005.61)
Timestamp: 1655392288  (Unix Timestamp)
     Date: Thursday, 16 June 2022
     Time: 8:41:28 PM  (India Standard Time, UTC+05:30)
--------------------------------------------------------------------
Traceback: File "c:\users\dipankar\python\python38-32\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "c:\users\dipankar\python\python38-32\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "C:\Users\Dipankar\Downloads\seleniumbase-tests-master\tests\test_contact.py", line 29, in test_contact_page
    self.assert_text("Thanks for us! We will be in touch with you shortly", "div[role=alert]")
  File "c:\users\dipankar\python\python38-32\lib\site-packages\seleniumbase\fixtures\base_case.py", line 9973, in assert_text
    self.wait_for_text_visible(text, selector, by=by, timeout=timeout)
  File "c:\users\dipankar\python\python38-32\lib\site-packages\seleniumbase\fixtures\base_case.py", line 9898, in wait_for_text_visible
    return page_actions.wait_for_text_visible(
  File "c:\users\dipankar\python\python38-32\lib\site-packages\seleniumbase\fixtures\page_actions.py", line 511, in wait_for_text_visible
    timeout_exception(TextNotVisibleException, message)
  File "c:\users\dipankar\python\python38-32\lib\site-packages\seleniumbase\fixtures\page_actions.py", line 162, in timeout_exception
    raise exc(msg)
Exception: Message: 
 Expected text substring {Thanks for us! We will be in touch with you shortly} for {div[role=alert]} was not visible after 7 seconds!
 (The string searched was {Thanks for contacting us! We will be in touch with you shortly})
